baseURL = 'https://coffeeshopastrophysics.github.io/'
relativeURLs = true
canonifyURLs = true
languageCode = 'en-us'
title = 'Coffee Shop Astrophysics'
theme = 'csa'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Talks'
    pageRef = '/talks'
    weight = 20

  [[menus.main]]
    name = 'Members'
    pageRef = '/members'
    weight = 25

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 30

  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 40
